type Query {
  activeGames: [Game]
  getUser(id: ID!): User
  me: User
}

type Mutation {
  hostGame: Game!
  joinGame(gameId: ID!): Game
  updateMe(name: String, publicKey: String): User!
}

type Subscription {
  gameUpdated: Game!
}

type User {
  id: ID!
  name: String
  publicKey: String
  endpoints: [String]
}

type UserPrivate {
  id: ID!
  email: String
}

type Game {
  id: ID!
  gameName: String
  host: User
  peers: [User]
  active: Boolean
}
